### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by mycve** [wyzxxz/shiro_rce_tool#22]
希望添加一个选项参数,在发现可利用的时候跳过利用直接进程结束.
不然进程阻塞头大

**Comment by wyzxxz** [comment]
加好了
java -jar  shiro_tool.jar https://xx.xx.xx.xx/  notcheckall

**Comment by mycve** [comment]
> 

我的意思是检测到程序结束,而不是让选择执行命令等待获取输入...
因为用其他程序调用它,不好检测它是否以及结束.

**Comment by wyzxxz** [comment]
java -jar shiro_tool.jar https://xx.xx.xx.xx/ getgadget
