### ISSUE TITLE
建议添加返回输出

### ISSUE THREAD

**Issue by Tukali** [wyzxxz/shiro_rce_tool#26]
建议师傅添加一个输出返回，在找到正确的key后返回响应包的内容，这样就可以判断是否是误报（waf,报错页面等），现在就遇到运行一次找到的key都不一样，不好判断返回，或者直接加个代理选项然后能够抓包判断也行

**Comment by wyzxxz** [comment]
加了其他校验，你下载最新的看看，如果还不行，再加这个。

**Comment by Tukali** [comment]
> 加了其他校验，你下载最新的看看，如果还不行，再加这个。

好的，谢谢师傅，我先关了issue，后面碰到不行的再来问您
