### ISSUE TITLE
最新发布的jar包，执行报错-错误：找不到或无法加载主类 shiro.Shiro

### ISSUE THREAD

**Issue by zhaojian320602** [wyzxxz/shiro_rce_tool#27]
![image](https://user-images.githubusercontent.com/79327313/184088591-593cc800-7f06-4a20-bb1f-0b2c500960d8.png)
最新发布的jar包，我在多台电脑，多个环境上尝试了均报此错误，上一个版本我没发现此问题，未解析jar包查找报错原因

**Comment by wyzxxz** [comment]
好了，传错了
